### ISSUE TITLE
Missing packages: scikit-learn and ijson

### ISSUE THREAD

**Issue by stephengmatthews** [sdpython/pandas-streaming#39]
Pip doesn't install all required packages. It seems that scikit-learn and ijson are missing.

The steps to demonstrate that scikit-learn is missing:
```bash
python -m venv venv
source venv/bin/activate
pip install pandas-streaming
python -c "import pandas_streaming.df"
```
And, the output:
```bash
ModuleNotFoundError: No module named 'sklearn'
```

The steps to demonstrate that ijson is missing:
```bash
pip install scikit-learn
python -c "import pandas_streaming.df"
```
And, the output:
```bash
ModuleNotFoundError: No module named 'ijson'
```

**Comment by ybressler** [comment]
I had the same issue. Consider storing dependencies explicitly in `pyproject.toml`. (I personally like poetry as a dep manager)
